const records = [
  {
    firstName: "Abebech",
    lastName: "Bersabeh",
    // phoneNumber: "09124115125",
    date: "10-10-2021",
    visitTime: "12:40PM",
    radiologist: "Dr.Someone",
    radiographer: "Dr.Radiographer",
    condition: "Bacterial Puemonia",
    status: "requested",
    priority: "emergency",
    age: 33,
    sex: "male",
  },
  {
    firstName: "Abebech",
    lastName: "Bersabeh",
    // phoneNumber: "09124115125",
    date: "10-10-2021",
    visitTime: "12:40PM",
    radiologist: "Dr.Someone",
    radiographer: "Dr.Radiographer",
    condition: "Bacterial Puemonia",
    status: "diagnosed",
    priority: "emergency",
    age: 33,
    sex: "male",
  },
  {
    firstName: "Abebech",
    lastName: "Bersabeh",
    // phoneNumber: "09124115125",
    date: "10-10-2021",
    visitTime: "12:40PM",
    radiologist: "Dr.Someone",
    radiographer: "Dr.Radiographer",
    condition: "Bacterial Puemonia",
    status: "requested",
    priority: "emergency",
    age: 33,
    sex: "male",
  },
  {
    firstName: "Abebech",
    lastName: "Bersabeh",
    // phoneNumber: "09124115125",
    date: "10-10-2021",
    visitTime: "12:40PM",
    radiologist: "Dr.Someone",
    radiographer: "Dr.Radiographer",
    condition: "Bacterial Puemonia",
    status: "Imaged",
    priority: "emergency",
    age: 33,
    sex: "male",
  },

  {
    firstName: "Abebech",
    lastName: "Bersabeh",
    // phoneNumber: "09124115125",
    date: "10-10-2021",
    visitTime: "12:40PM",
    radiologist: "Dr.Someone",
    radiographer: "Dr.Radiographer",
    condition: "Bacterial Puemonia",
    status: "diagnosed",
    priority: "emergency",
    age: 33,
    sex: "male",
  },
  {
    firstName: "Abebech",
    lastName: "Bersabeh",
    // phoneNumber: "09124115125",
    date: "10-10-2021",
    visitTime: "12:40PM",
    radiologist: "Dr.Someone",
    radiographer: "Dr.Radiographer",
    condition: "Bacterial Puemonia",
    status: "requested",
    priority: "emergency",
    age: 33,
    sex: "male",
  },

  {
    firstName: "Abebech",
    lastName: "Bersabeh",
    // phoneNumber: "09124115125",
    date: "10-10-2021",
    visitTime: "12:40PM",
    radiologist: "Dr.Someone",
    radiographer: "Dr.Radiographer",
    condition: "Bacterial Puemonia",
    status: "Imaged",
    priority: "emergency",
    age: 33,
    sex: "male",
  },
  {
    firstName: "Abebech",
    lastName: "Bersabeh",
    // phoneNumber: "09124115125",
    date: "10-10-2021",
    visitTime: "12:40PM",
    radiologist: "Dr.Someone",
    radiographer: "Dr.Radiographer",
    condition: "Bacterial Puemonia",
    status: "Imaged",
    priority: "emergency",
    age: 33,
    sex: "male",
  },
];

export { records };
